Repository framgia/sph-ojt-compendium, pull requests merged in 2022-08, with the labels that each got.

#2 [SPH-TASK] [FE] Initial Commit
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/pull_request_template.md
  fe/src/App.css
  fe/src/App.js
  fe/src/App.test.js
  fe/src/index.css
  fe/src/index.js
  fe/src/logo.svg
  fe/src/reportWebVitals.js
  fe/src/setupTests.js
Labels: reviewing tag, Approved by Roy, Approved by Joshua

#1 [SPH-TASK]Connecting to MySQL Database
  .gitignore
  be/compendium/compendium/.env.example
  be/compendium/compendium/settings.py
  be/compendium/db/__init__.py
  be/compendium/db/admin.py
  be/compendium/db/apps.py
  be/compendium/db/migrations/0001_initial.py
  be/compendium/db/migrations/__init__.py
  be/compendium/db/models.py
  be/compendium/db/tests.py
  be/compendium/db/views.py
Labels: Approved by Rose, Approved by David

#6 [SPH-TASK] [FE] Daily-Report(Create)
  be/compendium/compendium/.env.example
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.js
  fe/src/pages/Comments/Create/CommentCreate.js
  fe/src/pages/Comments/Create/CommentCreate.module.css
Labels: Approved by Joshua

#8 [SPH-TASK] [BE] Daily Report (Create)
  .gitignore
  be/compendium/compendium/settings.py
  be/compendium/compendium/urls.py
  be/compendium/db/apps.py
  be/compendium/db/migrations/0002_remove_users_account_id_users_account_and_more.py
  be/compendium/db/models.py
  be/compendium/db/serializers.py
  be/compendium/db/views.py
Labels: Approved by Rose, Approved by Nina

#4 [SPH-OJT][BE] - Added early endpoints for daily reports
  .gitignore
  be/compendium/compendium/.env.example
  be/compendium/compendium/models.py
  be/compendium/compendium/settings.py
  be/compendium/compendium/urls.py
  be/compendium/db/models.py
  be/compendium/db/serializers.py
  be/compendium/db/views.py
  be/requirements.txt
Labels: rose is reviewing, Approved by Vandam

#10 [SPH-TASK] [FE] Login-Register (Routes)
  fe/public/favicon.ico
  fe/public/images/logo.png
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.js
  fe/src/App.test.js
  fe/src/index.css
  fe/src/index.js
  fe/src/logo.svg
  fe/src/pages/Home.js
  fe/src/pages/Login.js
  fe/src/pages/Register.js
  fe/src/pages/RegisterSuccess.js
  fe/src/pages/UpdateDailyReport.js
  fe/src/reportWebVitals.js
  fe/src/setupTests.js
Labels: Approved by Joshua, Approved by Nina, Reviewed by Clement

#9 [SPH TASK] [FE] Profile
  fe/package-lock.json
  fe/package.json
  fe/src/index.js
  fe/src/pages/Profile/UserProfile.js
  fe/src/pages/Profile/UserProfile.module.css
Labels: Approved by Joshua

#11 [SPH-Task][BE]Register and Login
  be/compendium/compendium/settings.py
  be/compendium/compendium/urls.py
  be/compendium/db/apps.py
  be/compendium/db/migrations/0003_user_alter_daily_reports_user_id_delete_users.py
  be/compendium/db/models.py
  be/compendium/db/serializers.py
  be/compendium/db/views.py
Labels: Approved by Rose, Approved by Vandam

#19 [SPH-TASK] Edit and Delete modals
  fe/public/images/logo2.png
  fe/src/index.js
  fe/src/pages/Comments/Create/CommentCreate.module.css
  fe/src/pages/DailyReport/DeleteDailyReport.js
  fe/src/pages/DailyReport/EditDailyReport.js
  fe/src/pages/Dummy.js
Labels: Approved by Joshua, Approved by Nina

#25 Recent Dashboard
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/index.js
  fe/src/pages/Dashboard/Dashboard.js
  fe/src/pages/Dashboard/Dashboard.module.css
  fe/src/pages/Dashboard/DashboardContent/DailyReports/DailyReportCard/DailyReportCard.js
  fe/src/pages/Dashboard/DashboardContent/DailyReports/DailyReportCard/DailyReportCard.module.css
  fe/src/pages/Dashboard/DashboardContent/DailyReports/DailyReportCard/package.json
  fe/src/pages/Dashboard/DashboardContent/DailyReports/DailyReports.js
  fe/src/pages/Dashboard/DashboardContent/DailyReports/DailyReports.module.css
  fe/src/pages/Dashboard/DashboardContent/DailyReports/package.json
  fe/src/pages/Dashboard/DashboardContent/DasboardContent.js
  fe/src/pages/Dashboard/DashboardContent/DashboardContent.module.css
  fe/src/pages/Dashboard/DashboardContent/Interns/Interns.js
  fe/src/pages/Dashboard/DashboardContent/Interns/Interns.module.css
  fe/src/pages/Dashboard/DashboardContent/Interns/package.json
  fe/src/pages/Dashboard/DashboardContent/Recent/Recent.js
  fe/src/pages/Dashboard/DashboardContent/Recent/Recent.module.css
  fe/src/pages/Dashboard/DashboardContent/Recent/package.json
  fe/src/pages/Dashboard/DashboardContent/UserProfile/UserProfile.js
  fe/src/pages/Dashboard/DashboardContent/UserProfile/UserProfile.module.css
  fe/src/pages/Dashboard/DashboardContent/UserProfile/package.json
  fe/src/pages/Dashboard/DashboardContent/package.json
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigation.js
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigation.module.css
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigatonButton/LeftNavigationButton.js
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigatonButton/LeftNavigationButton.module.css
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigatonButton/package.json
  fe/src/pages/Dashboard/LeftNavigation/avatar.svg
  fe/src/pages/Dashboard/LeftNavigation/dashboard.svg
  fe/src/pages/Dashboard/LeftNavigation/interns.svg
  fe/src/pages/Dashboard/LeftNavigation/logout.svg
  fe/src/pages/Dashboard/LeftNavigation/package.json
  fe/src/pages/Dashboard/LeftNavigation/profile.svg
  fe/src/pages/Dashboard/LeftNavigation/reports.svg
  fe/src/pages/Dashboard/package.json
  fe/src/pages/Login.js
Labels: Approved by Nina, Reviewed by Clement, To be Reviewed

#29 [SPH-TASK]Markup-Redone-Pages
  .gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/apis/Home.js
  fe/src/apis/Login.js
  fe/src/apis/Register.js
  fe/src/apis/RegisterSuccess.js
  fe/src/apis/UpdateDailyReport.js
  fe/src/pages/Home/Home.js
  fe/src/pages/Home/Home.module.css
  fe/src/pages/Login/Login.js
  fe/src/pages/Login/Login.module.css
  fe/src/pages/Login/components/Breakline/Breakline.js
  fe/src/pages/Login/components/Breakline/package.json
  fe/src/pages/Login/components/Dropdown/Dropdown.js
  fe/src/pages/Login/components/Dropdown/Dropdown.module.css
  fe/src/pages/Login/components/Dropdown/package.json
  fe/src/pages/Login/components/InputField/InputField.js
  fe/src/pages/Login/components/InputField/InputField.module.css
  fe/src/pages/Login/components/InputField/package.json
  fe/src/pages/Login/package.json
  fe/src/pages/Register/Register.js
  fe/src/pages/Register/Register.module.css
  fe/src/pages/Register/components/Breakline/Breakline.js
  fe/src/pages/Register/components/Breakline/package.json
  fe/src/pages/Register/components/Dropdown/Dropdown.js
  fe/src/pages/Register/components/Dropdown/Dropdown.module.css
  fe/src/pages/Register/components/Dropdown/package.json
  fe/src/pages/Register/components/InputField/InputField.js
  fe/src/pages/Register/components/InputField/InputField.module.css
  fe/src/pages/Register/components/InputField/package.json
  fe/src/pages/RegisterSuccess/RegisterSuccess.js
  fe/src/pages/RegisterSuccess/RegisterSuccess.module.css
Labels: Approved by Rose, Nina is Reviewing

#27 [SPH-OJT][FE]-Intern list dashboard
  fe/src/App.js
  fe/src/pages/Dashboard/DashboardContent/Interns/Interns.js
  fe/src/pages/Dashboard/DashboardContent/Interns/Interns.module.css
  fe/src/pages/Dashboard/DashboardContent/Interns/InternsCard/InternsCard.js
  fe/src/pages/Dashboard/DashboardContent/Interns/InternsCard/InternsCard.module.css
  fe/src/pages/Dashboard/DashboardContent/Interns/InternsCard/package.json
  fe/src/pages/Dashboard/DashboardContent/Interns/search.svg
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigatonButton/LeftNavigationButton.js
Labels: Approved by Nina, needs rebase, Approved by Clement, To be Reviewed

#31 [SPH-OJT][FE] - QUICK FIX ON ROUTES AND DETAILS
  fe/src/pages/Dashboard/DashboardContent/DasboardContent.js
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigation.js
  fe/src/pages/Dashboard/LeftNavigation/LeftNavigatonButton/LeftNavigationButton.js
Labels: Approved by Nina, Clement is reviewing

#30 [SPH-OJT] - Create Daily Report
  fe/src/App.js
  fe/src/pages/DailyReport/CreateDailyReport/CreateDailyReport.js
  fe/src/pages/DailyReport/CreateDailyReport/CreateDailyReport.module.css
  fe/src/pages/DailyReport/CreateDailyReport/back.svg
  fe/src/pages/DailyReport/CreateDailyReport/package.json
Labels: Approved by Nina, Reviewed by Clement

#24 [SPH-TASK] [Wireframes] User-Profile
  be/compendium/compendium/urls.py
  be/compendium/db/migrations/0003_user_alter_daily_reports_user_id_delete_users.py
  be/compendium/db/views.py
  fe/public/images/Back Button.png
  fe/public/images/editProfile.png
  fe/public/images/profile.png
  fe/public/index.html
  fe/src/App.js
  fe/src/index.js
  fe/src/pages/EditProfile/EditProfile.js
  fe/src/pages/EditProfile/Picture/Picture.js
  fe/src/pages/EditProfile/Picture/Picture.module.css
  fe/src/pages/EditProfile/components/BackArrow/BackArrow.js
  fe/src/pages/EditProfile/components/InputField/InputField.js
  fe/src/pages/EditProfile/components/InputField/InputField.module.css
  fe/src/pages/EditProfile/components/dropdown/Dropdown.js
  fe/src/pages/EditProfile/components/dropdown/Dropdown.module.css
  fe/src/pages/EditProfile/components/forms/Forms.js
  fe/src/pages/EditProfile/components/forms/Forms.module.css
  fe/src/pages/InternProfile/InternHistory/InternHistory.js
  fe/src/pages/InternProfile/InternHistory/internHistory.module.css
  fe/src/pages/InternProfile/InternInfo/InternInfo.js
  fe/src/pages/InternProfile/InternInfo/InternInfo.module.css
  fe/src/pages/InternProfile/pages/InternProfile.js
  fe/src/pages/Profile/UserProfile.js
  fe/src/pages/Profile/UserProfile.module.css
  fe/src/pages/userprofile/components/breakline/Breakline.js
  fe/src/pages/userprofile/components/button/BtnNavigate.js
  fe/src/pages/userprofile/components/button/Button.js
  fe/src/pages/userprofile/components/button/Button.module.css
  fe/src/pages/userprofile/components/button/btnNavigate.module.css
  fe/src/pages/userprofile/components/displaytext/DisplayText.js
  fe/src/pages/userprofile/components/displaytext/DisplayText.module.css
  fe/src/pages/userprofile/components/input/Input.js
  fe/src/pages/userprofile/components/input/Input.module.css
  fe/src/pages/userprofile/components/navbar/NavBar.js
  fe/src/pages/userprofile/components/navbar/NavBar.module.css
  fe/src/pages/userprofile/components/reportshistory/ReportsHistory.js
  fe/src/pages/userprofile/components/reportshistory/reportsHistory.module.css
  fe/src/pages/userprofile/components/userinfo/UserInfo.js
  fe/src/pages/userprofile/components/userinfo/UserInfo.module.css
  fe/src/pages/userprofile/labels/Label.js
  fe/src/pages/userprofile/labels/Label.module.css
  fe/src/pages/userprofile/pages/UserProfile.js
  markups/userprofile/src/pages/UserProfile.js
Labels: Reviewed by Clement, Nina is Reviewing
